[application]
name = "blogy"
out_dir = "docs"
public_dir = "public"

[web.app]
title = "blogy"
base_path = "blogy"

[web]
brotli_compression = true

[web.watcher]
reload_html = true
watch_path = ["src", "styles", "docs/assets/syntax", "public"]

[web.resource]
style = []
script = []

[web.resource.dev]
script = []
