[application]
base_path = "blogy"   # <-- MUST match your GitHub repo name
out_dir = "docs"        # <-- GH-Pages will serve this folder
[web]
brotli_compression = true
# repo name (or "" if you use a custom domain)

[web.app]

# HTML title tag content
title = "blogy"
out_dir = "docs"
#base_path = "blogy"   # <-- MUST match your GitHub repo name

# [web.tailwind]
# input  = "tailwind.css"      # the file that contains @import "tailwindcss"
# output = "assets/tailwind.css"  #
# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = [
]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
